on: [push]
name: Update phpinfo

jobs:
    phpinfo:
        name: phpinfo
        strategy:
            matrix:
                os: [ubuntu-16.04, ubuntu-18.04]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v1
            -   run: |
                    for VERSION in 5.6 7.0 7.1 7.2 7.3; do
                          php$VERSION ./post-phpinfo.php 5b592d89f348b0fef996c01604fc9eec ${{ matrix.os }}-php-$VERSION.txt <<< "${{secrets.GIST_TOKEN }}" || echo "Version $VERSION does not exist"
                    done
